"""Add audit trail fields (updated_by, updated_at) to PatientRecord model

Revision ID: 76f06c73280d
Revises: 8f41dced239f
Create Date: 2025-03-04 19:54:01.245637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f06c73280d'
down_revision = '8f41dced239f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###
