"""Updated Patient model with additional fields

Revision ID: 8f41dced239f
Revises: c32463f0779b
Create Date: 2025-02-24 19:16:44.380669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f41dced239f'
down_revision = 'c32463f0779b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), server_default='', nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), server_default='', nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('home_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('personal_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('medical_insurance', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('medical_insurance')
        batch_op.drop_column('occupation')
        batch_op.drop_column('personal_phone')
        batch_op.drop_column('home_phone')
        batch_op.drop_column('home_address')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
